### ISSUE TITLE
SesameSDKがGradleでダウンロードできません / Can't download SesameSDK using Graldle

### ISSUE THREAD

**Issue by engarnet** [CANDY-HOUSE/SesameSDK_Android_with_DemoApp#28]
## Japanese
`SesameSDK_Android` リポジトリが削除されているようで、
[SesameSDKをインストール](https://doc.candyhouse.co/ja/android/quick_start_android#sesamesdk%E3%82%92%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB) に記載されている方法でSesameSDKのAARファイルがダウンロードができません。

この影響でSesameSDKを使うアプリがビルドできなくなっているため、対応方法を教えていただきたいです。

## English
I can't download SesameSDK aar file according to [this page](https://doc.candyhouse.co/ja/android/quick_start_android#sesamesdk%E3%82%92%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB), because of missing `SesameSDK_Android` repository.

I can't build my app using SesameSDK, so please tell me how to deal this problem.

**Comment by engarnet** [comment]
SesameSDK_Android was reopened and I can download SesameSDK.

**Comment by Jerming** [comment]
https://github.com/CANDY-HOUSE/SesameSDK_Android_with_DemoApp/tree/5c3a51d3ea625e4338230c994b8b775bad9b17e4/SesameSDK_Android/co/candyhouse/jp/sesame/2.0.7

こちらのご使用をお願い申し上げます。

**Comment by engarnet** [comment]
@Jerming 
↑のaarを取得するためのmavenリポジトリのURLを教えてください。
以前は[ここ](https://doc.candyhouse.co/ja/android/quick_start_android#sesamesdk%E3%82%92%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB) に記載のある `https://github.com/CANDY-HOUSE/SesameSDK_Android/raw/main` でした。
