### ISSUE TITLE
SESAMI5とのBLE通信について

### ISSUE THREAD

**Issue by imammy-hacomono** [CANDY-HOUSE/SesameSDK_Android_with_DemoApp#32]
Hello @Jerming San.

## Japanese
平文でのSESAMI5とのBLE通信についていくつか教えて下さい。

1. Random Codeについて
SESAMI5とBLE接続後、Notifyを有効にすると「0x03080E********」というデータが受信されます。
08はレスポンスを表し、0Eは14なのでコマンドを表していると思いますが、
先頭の03とは何を表しているのでしょうか？
また、「********」という4byteのデータがRandom Codeとの事ですが、こちらの使い道が分かりません。。。
<br><br>

2. Lock/Unlockコマンドについて
Lockコマンド、Unlockコマンドをそれぞれ平文で投げようとしています。
ドキュメントを見ると、historyTagを7byte付加させるよう書いていますが、
何をつければ良いのか分からず、適当に0x00を7byte分付けています。
こちらの用途を教えていただけると助かります。
また、コマンドの前に0x03をつけると、Lock/Unlockコマンドが通ります（例：0x035200000000000000）
Random Codeについての質問と被りますが、こちらについても教えていただきたいです。
また、Lock/Unlockコマンドが通りますが、SESAMI5からのNotifyが（例：05EF9F6ACCEED4D8）となっています。
https://github.com/CANDY-HOUSE/SesameSDK_Android_with_DemoApp/blob/master/doc/class/SesameResultCode_jp.md
こちらの読み解き方を教えて頂きたいです。（暗号化されている？？）

![IMG_5204](https://github.com/CANDY-HOUSE/SesameSDK_Android_with_DemoApp/assets/122067348/75ec0e15-d8be-4746-a253-1e5a9805e339)
<br><br>

3. 現在のサムターンのアングルの取得方法
configureLockPositionコマンドで解錠位置と施錠位置のアングルを設定するために必要な、
現在のサムターンのアングル値の取得方法を知りたいです。
https://github.com/CANDY-HOUSE/SesameSDK_Android_with_DemoApp/blob/master/doc/command/configureLockPosition_jp.md
<br><br>

4. 接続から暗号文による通信が可能になるまでに必要なコマンドの一覧とそのフローについて
SESAMI5と暗号通信するために必要なコマンドとその順番を明記したフローや情報を教えて頂きたいです。
<br><br>

<br><br><br>

## English

Please provide me with some information about BLE communication with SESAMI5 in plain text.

1. About Random Code
After establishing a BLE connection with SESAMI5 and enabling Notify, the data "0x03080E********" is received.
In this sequence, '08' represents the response and '0E' represents the command (14). However, what does the leading '03' indicate?
Additionally, the 4-byte data denoted as "********" is referred to as the Random Code. However, I'm unsure about its intended purpose or usage...
<br><br>

2. About Lock/Unlock Commands:
I'm currently working on sending Lock and Unlock commands in plaintext. According to the documentation, it's mentioned to append a 7-byte historyTag, but I'm uncertain about what should be added. As a temporary measure, I've added 0x00 for 7 bytes. Could you kindly clarify the purpose of this field? Additionally, I've noticed that when I prefix the command with 0x03 (e.g., 0x035200000000000000), the Lock/Unlock command is successful. This query seems to overlap with the earlier question regarding the Random Code, and I would appreciate an explanation in this context as well. Furthermore, even though the Lock/Unlock command goes through successfully, the Notify from SESAMI5 returns as something like 05EF9F6ACCEED4D8. 
https://github.com/CANDY-HOUSE/SesameSDK_Android_with_DemoApp/blob/master/doc/class/SesameResultCode_jp.md
I'm seeking guidance on interpreting this, as provided in this GitHub link. Could you elaborate on how to decode this information? (Is it encrypted?)
<br><br>

3. Obtaining Current Thumb Turn Angle:
I'm interested in understanding the method for obtaining the present thumb turn angle. This information is necessary for configuring the lock/unlock positions using the configureLockPosition command.
<br><br>

4. List of Commands and Flow Required for Communication from Connection to Cipher Text:
I would like to receive information about the necessary commands and their sequence required to establish encrypted communication with SESAMI5. Please provide a detailed flow or information outlining the commands and their order for achieving encrypted communication with SESAMI5.

**Comment by imammy-hacomono** [comment]
@Jerming 
こちらいかがでしょうか？
SESAMIはSDK経由でしかアクセスさせません、という事であれば諦めるのですが。。。

**Comment by Jerming** [comment]
https://github.com/CANDY-HOUSE/Sesame_BluetoothAPI_document

どうぞ！
@imammy-hacomono
