### ISSUE TITLE
セサミ本体をリセットするためAPIはありますか？

### ISSUE THREAD

**Issue by rimihalt** [CANDY-HOUSE/SesameSDK_Android_with_DemoApp#45]
本体のリセットスイッチを押下しリセットすることを
SDKのAPIを使用して行うことは可能でしょうか？

**Comment by Jerming** [comment]
可能です！
そのAPIがございます。

**Comment by rimihalt** [comment]
ご回答ありがとうございます。
では、そのAPI関数がどれであるか教えていただけないでしょうか。
よろしくお願いいたします。
